GITA_QUOTES = [
    "Focus on your work, not the results. Excellence comes from dedication.",
    "Stay calm in success and failure. Balance leads to wisdom.",
    "Control your mind, for it can be your best friend or worst enemy.",
    "Work with full dedication, but remain detached from the outcome.",
    "Knowledge is power, but wisdom is knowing how to use it.",
    "Face challenges with courage. Every difficulty makes you stronger.",
    "Be present in this moment. Past and future exist only in the mind.",
    "Serve others selflessly. True joy comes from giving.",
    "Maintain equanimity in all situations. This is true strength.",
    "Your actions shape your character. Choose them wisely.",
    "Overcome fear with knowledge and faith in yourself.",
    "Practice patience and perseverance. Great things take time.",
    "Find peace within yourself. External circumstances change, but inner peace remains.",
    "Work is worship when done with the right intention.",
    "Transform obstacles into opportunities through positive thinking.",
    "Discipline your desires. True freedom comes from self-control.",
    "Share your knowledge and skills. Teaching others elevates you too.",
    "Maintain hope in difficult times. Dawn always follows the darkest hour.",
    "Be grateful for what you have. Contentment brings happiness.",
    "Live with purpose. Let your work contribute to something greater.",
    "The mind is restless, but it can be trained through practice and detachment.",
    "Those who are motivated only by desire for fruits are miserable.",
    "A wise person acts without attachment, seeking the welfare of all beings.",
    "Whatever happened was good. Whatever is happening is good. Whatever will happen will be good.",
    "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    "Even a little practice of this dharma protects one from great fear.",
    "Those who are devoted to selfless action attain peace.",
    "He who has conquered himself is greater than he who conquers a thousand men in battle.",
    "Do your duty and do not worry about the results.",
    "Change is the law of the universe. You can be a millionaire, or a pauper, in an instant.",
    "Man is made by his belief. As he believes, so he becomes.",
    "The soul is neither born, and nor does it die.",
    "When you feel the presence of the divine, fear disappears.",
    "Perform your obligatory duty, because action is indeed better than inaction.",
    "The key to happiness is the reduction of desires.",
    "There is nothing lost or wasted in this life.",
    "One who sees inaction in action, and action in inaction, is truly wise.",
    "Calmness, gentleness, silence, self-restraint, and purity—these are the disciplines of the mind.",
    "Those who are free from anger and all material desires, who are self-realized, and who are fully joyful, attain peace.",
    "The wise see the same in a learned scholar, a cow, an elephant, a dog, and an outcaste.",
    "You have the right to work, but never to the fruits thereof.",
    "A person can rise through the efforts of their own mind; or draw themselves down.",
    "One who has control over the mind is tranquil in heat and cold, pleasure and pain.",
    "Even if you are the most sinful of all sinners, you can cross all sin by the raft of knowledge.",
    "There is no purifier equal to knowledge.",
    "The one who sees me everywhere and sees everything in me, never becomes separated from me.",
    "The soul is eternal, indestructible, and infinite.",
    "Free from attachment, fear, and anger, fully absorbed in Me, many have become purified by knowledge.",
    "To the illumined soul, all beings are one.",
    "Even a little effort in the right direction brings protection from great fear.",
    "Perform every action with your heart fixed on the Supreme.",
    "The wise work for the welfare of the world.",
    "Whatever you do, whatever you eat, whatever you offer, do it as an offering unto Me.",
    "Those who are motivated only by desire for results cannot experience peace.",
    "A person who is not disturbed by happiness and distress, who is steady in both, is eligible for liberation.",
    "Those who are established in self-realization see all beings with equal vision.",
    "Lust, anger, and greed are the three gates to self-destruction.",
    "Renounce attachment to the fruits of your work, and find peace within yourself.",
    "Yoga is the journey of the self, through the self, to the self.",
    "He who acts without selfish motives is truly free.",
    "Where there is faith, there is victory.",
    "You become what you believe in.",
    "Peace comes from within. Do not seek it without.",
    "A gift given in the right place, to a worthy person, without expectation, is true charity.",
    "The wise see beyond appearances, into the unity behind all diversity.",
    "The self-controlled soul, who moves among sense objects, free from attachment and aversion, gains peace.",
    "Desire leads to anger, anger leads to delusion, and delusion leads to the loss of wisdom.",
    "Those who are motivated by love and compassion never fail in life.",
    "Even the smallest act done with love is sacred.",
    "True success is self-mastery, not external conquest.",
    "Self-realization is the highest form of knowledge.",
    "To conquer the mind is to conquer the world.",
    "The path of love is the path of peace.",
    "Wherever the mind wanders, bring it back to the awareness of the Self.",
    "True renunciation is not abandoning action but detaching from its results.",
    "One who performs duty without attachment attains the Supreme.",
    "He who sees inaction in action, and action in inaction, is the wisest of men.",
    "A person who has found peace within themselves will find peace everywhere.",
    "Let go of expectations; live in surrender.",
    "The wise never grieve for the living or the dead.",
    "There is no greater strength than calmness under pressure.",
    "The body is temporary, but the soul is eternal.",
    "He who is content with whatever comes, free from envy, and steady in success or failure, is truly wise.",
    "A disciplined mind leads to happiness; an undisciplined one leads to suffering.",
    "Do not let success or failure affect your purpose.",
    "Even the darkest night will end, and the sun will rise.",
    "Selfless action is the true path to freedom.",
    "When you control your senses, you attain peace.",
    "Faith in yourself and the Divine can move mountains.",
    "See the Divine in all beings and all beings in the Divine.",
    "Patience, tolerance, and forgiveness are the marks of a true devotee.",
    "Victory over the self is greater than victory over thousands.",
    "The one who gives up selfish attachment is truly happy.",
    "Be still and know that you are eternal.",
    "Love is the language of the Divine.",
    "Meditate on the Supreme, and you shall find eternal joy.",
    "Your duty is to act, not to expect results.",
    "Whatever you do, do it as an offering of love.",
    "Those who are devoted to the path of service reach Me easily.",
    "One who is steady in happiness and distress is dear to Me.",
    "Selfless service purifies the heart.",
    "The more you let go, the more peace you find.",
    "The path of knowledge leads to unity with the Divine.",
    "Where there is righteousness, there is victory.",
    "When you surrender the fruits of your work, you are truly free.",
    "Even a moment of remembrance of the Divine destroys fear.",
    "Through faith and devotion, all doubts are destroyed.",
    "The wise act in harmony with nature, not against it.",
    "Do not let your mind be disturbed by anything.",
    "Act with a pure heart, and success will follow naturally.",
    "Your mind is your greatest tool—master it.",
    "To see the same God in all beings is the highest realization.",
    "He who has faith and self-control attains supreme peace.",
    "Renounce attachment, and find bliss within.",
    "The Divine is within you—seek there, not outside.",
    "One who sees unity in diversity truly knows Me.",
    "Purity of thought leads to purity of life.",
    "Freedom is found not in doing what you want, but in mastering desire.",
    "The light of wisdom dispels the darkness of ignorance.",
    "A calm mind is the foundation of true happiness.",
    "Perform your duties sincerely and leave the rest to the Divine.",
    "True wealth is contentment.",
    "The wise are not attached to pleasure or pain.",
    "Faith gives strength to the heart.",
    "Nothing in this world is permanent; find peace in the eternal.",
    "When your mind is steady, you experience true joy.",
    "Surrender to the Divine and be fearless.",
    "The Lord dwells in the hearts of all beings.",
    "Whatever you do with devotion becomes worship.",
    "Knowledge, devotion, and action are paths to the same goal.",
    "Live in harmony with yourself and the world.",
    "Happiness comes when your thoughts, words, and actions are in alignment.",
    "The power of the mind is limitless when guided by faith.",
    "Serve all beings with love and compassion.",
    "Be humble in success and graceful in failure.",
    "Detachment is not indifference; it is inner freedom.",
    "Self-discipline is the bridge between goals and accomplishment.",
    "Seek not perfection, but sincerity.",
    "The true yogi sees the Divine in all.",
    "You are what your deep, driving desire is.",
    "Let go of pride and ego, and peace will enter your heart.",
    "To see the world as it truly is, purify your heart.",
    "All that exists is pervaded by the Supreme.",
    "Act out of love, not obligation.",
    "The heart that loves all beings is closest to the Divine.",
    "Be fearless and upright in your actions.",
    "The Divine helps those who help themselves.",
    "In giving, we receive; in serving, we are uplifted.",
    "To control anger is to win over the greatest enemy.",
    "Life is a reflection of your inner state.",
    "When you stop chasing outcomes, you start living in peace.",
    "The more selfless your actions, the more divine they become.",
    "Through constant practice and patience, anything is achievable.",
    "Wisdom dawns when the mind becomes still.",
    "True love expects nothing in return.",
    "Act with integrity, and success will follow.",
    "The journey inward is the greatest adventure.",
    "The heart knows what the mind cannot understand.",
    "Meditation is the art of silencing the noise within.",
    "When you align with the Divine will, everything flows effortlessly.",
    "Compassion is the highest form of strength.",
    "You are never alone—the Divine is always within you.",
    "The one who finds joy in service lives in peace.",
    "Act with clarity, speak with kindness, and live with purpose.",
    "Forgiveness liberates the soul.",
    "Patience is the ornament of the wise.",
    "Let go of control, and trust the Divine plan.",
    "Your destiny unfolds according to your faith and actions.",
    "Through self-realization, all fear disappears.",
    "The flame of devotion never extinguishes.",
    "Act without attachment, and the world cannot bind you.",
    "See God in every heart and every heart in God.",
    "He who is content with whatever comes is truly rich.",
    "The highest wisdom is to know yourself as Divine.",
    "Peace begins the moment you accept what is.",
    "The soul is untouched by pleasure or pain.",
    "Every breath is a gift—live it with gratitude.",
    "Act with awareness, not impulse.",
    "The Lord loves the pure of heart.",
    "True faith transforms obstacles into blessings.",
    "When the mind becomes still, the soul shines through.",
    "Be the calm in the storm.",
]
